module.exports = [
  {label: 'Abia', value: 'Abia'},
  {label: 'Adamawa', value: 'Adamawa'},
  {label: 'Akwa Ibom', value: 'Akwa Ibom'},
  {label: 'Anambra', value: 'Anambra'},
  {label: 'Bauchi', value: 'Bauchi'},
  {label: 'Benue', value: 'Benue'},
  {label: 'Borno', value: 'Borno'},
  {label: 'Bayelsa', value: 'Bayelsa'},
  {label: 'Cross River', value: 'Cross River'},
  {label: 'Delta', value: 'Delta'},
  {label: 'Ebonyi', value: 'Ebonyi'},
  {label: 'Edo', value: 'Edo'},
  {label: 'Ekiti', value: 'Ekiti'},
  {label: 'Enugu', value: 'Enugu'},
  {label: 'Federal Capital Territory', value: 'Federal Capital Territory'},
  {label: 'Gombe', value: 'Gombe'},
  {label: 'Jigawa', value: 'Jigawa'},
  {label: 'Imo', value: 'Imo'},
  {label: 'Kaduna', value: 'Kaduna'},
  {label: 'Kebbi', value: 'Kebbi'},
  {label: 'Kano', value: 'Kano'},
  {label: 'Kogi', value: 'Kogi'},
  {label: 'Lagos', value: 'Lagos'},
  {label: 'Katsina', value: 'Katsina'},
  {label: 'Kwara', value: 'Kwara'},
  {label: 'Nasarawa', value: 'Nasarawa'},
  {label: 'Niger', value: 'Niger'},
  {label: 'Ogun', value: 'Ogun'},
  {label: 'Ondo', value: 'Ondo'},
  {label: 'Oyo', value: 'Oyo'},
  {label: 'Osun', value: 'Edo'},
  {label: 'Rivers', value: 'Rivers'},
  {label: 'Sokoto', value: 'Sokoto'},
  {label: 'Plateau', value: 'Plateau'},
  {label: 'Taraba', value: 'Taraba'},
  {label: 'Yobe', value: 'Yobe'},
  {label: 'Zamfara', value: 'Zamfara'},
];
